# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
      - master
  paths:
      include:
      - src/common/*
      exclude:
      - src/common/README.md

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: 'src/common/**/*.sln'
      feedsToUse: 'select'
      vstsFeed: 'd4b07e43-bd8a-40b6-8de0-3a0cca5cdd48'
  
  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 
      checkLatest: true
  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: 'src/common/BizzPo.Core/*.csproj'
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '$(Major)'
      minorVersion: '$(Minor)'
      patchVersion: '$(Patch)'

  - task: NuGetAuthenticate@0
    inputs:
      nuGetServiceConnections: 'BizzPo Nuget'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      feedsToUse: 'select'
      includeNugetOrg: true
  
