# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
      include:
      - master
  paths:
      include:
      - src/common/*
      exclude:
      - src/common/README.md

variables:
  Major: '1'
  Minor: '0'
  Patch: '0'
  configuration: 'Release'
  project: 'src/common/BizzPo.Core/*.csproj'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      configuration: $(configuration)
      projects: $(project)
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'pack'
      configuration: $(configuration)
      packagesToPack: $(project)
      nobuild: true
      versioningScheme: 'byPrereleaseNumber'
      majorVersion: '$(Major)'
      minorVersion: '$(Minor)'
      patchVersion: '$(Patch)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'